#!/bin/bash -e

INSTALL_PREFIX=${HOME}/.local

# Build and install LLVM
LLVM_SRC_DIR="third_party/llvm-project"
LLVM_BUILD_DIR="${LLVM_SRC_DIR}/build"
mkdir -p ${LLVM_BUILD_DIR}
pushd ${LLVM_BUILD_DIR}
cmake -DCMAKE_BUILD_TYPE=Release \
      -DLLVM_ENABLE_RTTI=ON \
      -DLLVM_TARGETS_TO_BUILD="X86;NVPTX" \
      -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="NVPTX" \
      -DLLVM_ENABLE_BINDINGS=OFF \
      -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;mlir" \
      -DLLVM_ENABLE_RUNTIMES="libc;libcxx;libcxxabi;libunwind" \
      -DLLVM_ENABLE_ZLIB=OFF \
      -DLLVM_ENABLE_ZSTD=OFF \
      -DLLVM_ENABLE_TERMINFO=OFF \
      -DLLVM_BUILD_LLVM_DYLIB=ON \
      -DLLVM_LINK_LLVM_DYLIB=ON \
      -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
      ../llvm
make -j $(nproc)
make install
popd

# Build and install Apache Arrow
ARROW_SRC_DIR="third_party/arrow/cpp/"
ARROW_BUILD_DIR="${ARROW_SRC_DIR}/build"
mkdir -p ${ARROW_BUILD_DIR}
pushd ${ARROW_BUILD_DIR}
cmake -DARROW_BUILD_STATIC=OFF \
      -DARROW_COMPUTE=ON \
      -DARROW_CSV=ON \
      -DARROW_DATASET=ON \
      -DARROW_FILESYSTEM=ON \
      -DARROW_JSON=ON \
      -DARROW_WITH_RE2=OFF \
      -DARROW_WITH_UTF8PROC=OFF \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
      ..
make -j $(nproc)
make install
popd

# Build Z3 solver
Z3_SRC_DIR="third_party/z3/"
Z3_BUILD_DIR="${Z3_SRC_DIR}/build"
mkdir -p ${Z3_BUILD_DIR}
pushd ${Z3_BUILD_DIR}
cmake -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
      ..
make -j $(nproc)
make install
popd

# Build PyBind11
PYBIND_SRC_DIR="third_party/pybind11/"
PYBIND_BUILD_DIR="${PYBIND_SRC_DIR}/build"
mkdir -p ${PYBIND_BUILD_DIR}
pushd ${PYBIND_BUILD_DIR}
cmake -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
      ..
make -j $(nproc)
make install
popd

# Build Reffine
REFFINE_BUILD_DIR="build/"
mkdir -p ${REFFINE_BUILD_DIR}
pushd ${REFFINE_BUILD_DIR}
cmake -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_PREFIX_PATH=${INSTALL_PREFIX} \
      -DENABLE_CUDA=ON \
      ..
make -j $(nproc)
popd
